### ISSUE TITLE
Models.py, Unresolved reference - from etc.toolbox import get_model_class_from_string

### ISSUE THREAD

**Issue by georgy95** [idlesign/django-siteflags#1]
The app fails to start:

>   File "/myapp/siteflags/models.py", line 10, in <module>
>     from etc.toolbox import get_model_class_from_string
> ModuleNotFoundError: No module named 'etc'

**Comment by idlesign** [comment]
Install `siteflags` with `pip` and it'll  install `django-etc` as a dependency.

**Comment by georgy95** [comment]
Thanks
