### ISSUE TITLE
using the variable "id" in myapp/views.py

### ISSUE THREAD

**Issue by LS4203** [idlesign/django-siteflags#4]
When I use the following method 

```
def article_details(request, id):
    article = get_object_or_404(Article, pk=id)
```
I get the warning 

> Shadows built-in name 'id' less... 
> Inspection info: This inspection detects shadowing built-in names, such as 'len' or 'list'

Can you kindly help on fixing this issue

**Comment by idlesign** [comment]
It's not ``siteflags`` specific your IDE (or linter) says that name ``id`` used in function overrides the builtin function ``id()``, thus making the builtin function basicly unavailable in current scope.

**Comment by LS4203** [comment]
Hi idledesign, as I am beginner in this, it took me a while to figure it own it was IDE specific. 

It should be for example, something like this:

```
def user_bookmarked_video(request, bookmark_id):
    video = get_object_or_404(Video, pk=bookmark_id)
    # Now a user adds this article to his bookmarks.

    video.set_flag(request.user)
```
