### ISSUE TITLE
Noobs find your instructions rather shorter than expected

### ISSUE THREAD

**Issue by LS4203** [idlesign/django-siteflags#5]
I have posted a question regarding your repo on stackoverflow due to lack of tutorials and understanding for noobs here [Stackoverflow question](https://stackoverflow.com/questions/55391168/how-to-use-django-siteflags-to-bookmark-site-objects)

Can you please help clarify that ? thank you

**Comment by idlesign** [comment]
Answered there.

**Comment by LS4203** [comment]
How to use django-siteflags to set and remove flags ?

Here is my **models.py** file

```
    class Video(ModelWithFlag, models.Model):
        name = models.CharField(max_length=255)
        file = models.FileField(upload_to="static/videos/", null=True, verbose_name="", unique=True)
        favourite = models.ManyToManyField(ProjectUser, related_name="fav_videos", blank=True)

    
        def __str__(self):
            return self.name
```

The **urls.py** 

    `path('favourite_post/<int:flag_id>/', views.set_flag, name='videos_flagged'),`



And the **views.py** file


```
def set_flag(request, flag_id):
    video = get_object_or_404(Video, pk=flag_id)
    # Now a user adds this article to his bookmarks.
    if video.is_flagged:
        video.remove_flag(request.user, status=0)
        video.save()
        print(f"This is video if flagged response {video}")
    else:
        video.set_flag(request.user, status=True)
        video.save()
        print(f"This is video else not flagged response {video}")

    return redirect('/video_overview/%s' % flag_id)
```



Everytime I click on the bookmark page, seems like it is not getting flagged. Here is the screenshot of repititve clicks on the `set_fliag`

![InkedCapture_LI](https://user-images.githubusercontent.com/47980161/55284687-d029e480-537b-11e9-8b75-4efca753a290.jpg)

**Comment by idlesign** [comment]
Did you check the docs? https://github.com/idlesign/django-siteflags/blob/master/docs/source/quickstart.rst
``is_flagged`` is not a property.
