### ISSUE TITLE
AJAX template for flag switching

### ISSUE THREAD

**Issue by BoPeng** [idlesign/django-siteflags#6]
It would be nice for this app to provide some frontend template for setting and clearing flags, like what packages such as `django-star-ratings` provide.

As a background I am trying to add two buttons like the `star` and `watch` buttons on this github page, one for "Bookmark" and one for "Star". A user should be able to "Bookmark"/"Unbookmark", "Star"/"Unstar" from the page with number of bookmarked users and stared users displayed instantly, and users would be able to see lists of bookmarked and starred items. The "instant change" part would need AJAX forms.

**Comment by idlesign** [comment]
Thank you for the idea.

But I'm afraid it may be not feasible to come up with a generic solution that satisfies most needs (js, urls, data passed). If you have any ideas, welcome.

Conserning your needs: in my `pythonz` project I use https://github.com/idlesign/django-xross to set votes and bookmarks as follows:

* See `toggle_bookmark` - it's a bookmark handle: https://github.com/idlesign/pythonz/blob/master/pythonz/apps/generics/views.py#L294
* We tie AJAX handlers with `@xross_view` decorator: https://github.com/idlesign/pythonz/blob/master/pythonz/apps/generics/views.py#L359 
* Inside view we use `xross_listener` dispatch function: https://github.com/idlesign/pythonz/blob/master/pythonz/apps/generics/views.py#L371
* In template we just markup html elements with `data-x...` attributes: https://github.com/idlesign/pythonz/blob/master/pythonz/apps/templates/sub/box_bookmark.html#L5

`django-xross` is a bit old and it's JS needs a refresher, but it works for me.

**Comment by BoPeng** [comment]
Thanks for your suggestion and examples, which helped me get the buttons implemented.
