### ISSUE TITLE
Double flag on the same object with the same user.

### ISSUE THREAD

**Issue by suprmat95** [idlesign/django-siteflags#8]
Hi everyone, I'm Matteo and I use django-siteflags in a project and I  found out a strange behaviour that could be a bug. 

```
 def test_set_flag(self, user, create_article):

        flag = create_article().set_flag(user, note='anote', status=10)

        assert flag.user == user
        assert flag.note == 'anote'
        assert flag.status == 10

        article_1 = create_article()
        article_1.set_flag(user)
        article_1.set_flag(user)
        flags = ModelWithFlag.get_flags_for_objects([article_1])
        assert len(flags[article_1.pk]) == 1
```

the last assert fails because it is equal two, but shouldn't it be one, since there shouldn't be duplicate flags?

**Comment by idlesign** [comment]
Hi,

This is intended to cover more use cases: flags are unique for object+user+status. At the same time status is ``None`` by default, so that you can set as many flags as you want.
If you need one flag per object+user just set ``status``.

**Comment by suprmat95** [comment]
Hi @idlesign, Thank you for your answer. Excuse me but yesterday in the test I did not set the status, but in my project I did it, the status is always set and despite this, I often find double flags in my database. The project is a web application where multiple requests can arrive at the same time.

**Comment by idlesign** [comment]
Please check that there's a unique constraint in DB as per
https://github.com/idlesign/django-siteflags/blob/master/siteflags/models.py#L55

**Comment by suprmat95** [comment]
Thank you very much I solved my problem!!

**Comment by idlesign** [comment]
@suprmat95 Constraints were somehow missing?

**Comment by suprmat95** [comment]
Yes, now our meta class inherits from FlagBase.Meta, thanks.

**Comment by idlesign** [comment]
I've added a note in docs https://github.com/idlesign/django-siteflags/commit/49d1cac199018de4aa8ea23acd58ed8e2984988e

Considered closed. 
Feel free to reopen if required.

**Comment by suprmat95** [comment]
Hi @idlesign I hope you're fine, I still have this problem, in fact, I find two rows with the same object_id and the same user_id:
![image](https://user-images.githubusercontent.com/11753185/104330269-1f5bed80-54ee-11eb-85a0-3f3145cf25cf.png)
 I don't know how it happens, do you have any advice?

**Comment by idlesign** [comment]
Hi,

You should probably verify constraints work with raw INSERT query. 
If you're able to insert the same 'content_type' + 'object_id' + 'user' + 'status', it'd mean that constraints do not work.

**Comment by suprmat95** [comment]
you are right, it doesn't work. I can put more rows with the same 'object_id'  and 'user'. Do you have any idea to solve this?

**Comment by idlesign** [comment]
Just create the constraint manually or using Django migrations machinery.
I thought you did just that after inheriting Meta to solve the issue.

**Comment by suprmat95** [comment]
I migrate and i solved it, thankyou!
